name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'FileStub-Vanguard'
    - name: Checkout RTCV peer dependency
      uses: actions/checkout@v2
      with:
        repository: 'redscientistlabs/RTCV'
        ref: '506'
        path: 'RTCV'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore Nuget packages in RTCV
      run: msbuild /t:restore '.\RTCV\'
    - name: Restore Nuget packages in FileStub-Vanguard
      run: msbuild /t:restore '.\FileStub-Vanguard\FileStub-Vanguard.sln'
    - name: Build with MSBuild
      run: msbuild '.\FileStub-Vanguard\FileStub-Vanguard.sln'
